services:
  web:
    build:
      context: ./../web
      dockerfile: Dockerfile
    container_name: web
    expose:
      - "3000"
    environment:
      - PORT=3000
      - API_BASE_URL=http://server:3001
      - PUBLIC_API_BASE_URL=http://localhost:80/api
    networks:
      - frontend

  server:
    build:
      context: ./../server
      dockerfile: Dockerfile
    container_name: server
    expose:
      - "3001"
    environment:
      - ASPNETCORE_URLS=http://+:3001
    networks:
      - frontend

  proxy:
    image: nginx:stable-alpine
    container_name: proxy
    depends_on:
      - web
      - server
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
